// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yjanxunjmvwqowzoiaeq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlqYW54dW5qbXZ3cW93em9pYWVxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0NTI4NDIsImV4cCI6MjA3MjAyODg0Mn0.KBJ3h_nK0XuNFtbfcUCJEl2JqwGUlp-m6UCVbGoDfOw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});